const byte Zone_Count = 4;

#define count_of(A) (sizeof(A)/sizeof(A[0]))
const byte patch_empty_zone[] = {-1};

// Generated by make patches.h:

// Patch built from check_sliders.patch
  const byte patch_check_sliders_z0[] = {0,1,2,3,4,5,-1};
const byte* patch_check_sliders[Zone_Count] = {patch_check_sliders_z0, patch_empty_zone, patch_empty_zone, patch_empty_zone};

// Patch built from [1] check_sliders.patch
  const byte patch_check_sliders_1_z1[] = {0,1,2,3,4,5,-1};
const byte* patch_check_sliders_1[Zone_Count] = {patch_empty_zone, patch_check_sliders_1_z1, patch_empty_zone, patch_empty_zone};

// Patch built from [2] check_sliders.patch
  const byte patch_check_sliders_2_z2[] = {0,1,2,3,4,5,-1};
const byte* patch_check_sliders_2[Zone_Count] = {patch_empty_zone, patch_empty_zone, patch_check_sliders_2_z2, patch_empty_zone};

// Patch built from [3] check_sliders.patch
  const byte patch_check_sliders_3_z3[] = {0,1,2,3,4,5,-1};
const byte* patch_check_sliders_3[Zone_Count] = {patch_empty_zone, patch_empty_zone, patch_empty_zone, patch_check_sliders_3_z3};

// Patch built from [test_all1] test.patch
  const byte patch_test_test_all1_z0[] = {0,1,2,3,4,-1};
const byte* patch_test_test_all1[Zone_Count] = {patch_test_test_all1_z0, patch_empty_zone, patch_empty_zone, patch_empty_zone};

// Patch built from [test_even_odd] test.patch
  const byte patch_test_test_even_odd_z0[] = {0,2,4,-1};
  const byte patch_test_test_even_odd_z1[] = {1,3,-1};
const byte* patch_test_test_even_odd[Zone_Count] = {patch_test_test_even_odd_z0, patch_test_test_even_odd_z1, patch_empty_zone, patch_empty_zone};

// Patch built from [test_zones_on_one] test.patch
  const byte patch_test_test_zones_on_one_z0[] = {0,-1};
  const byte patch_test_test_zones_on_one_z1[] = {1,-1};
  const byte patch_test_test_zones_on_one_z2[] = {2,-1};
  const byte patch_test_test_zones_on_one_z3[] = {3,4,-1};
const byte* patch_test_test_zones_on_one[Zone_Count] = {patch_test_test_zones_on_one_z0, patch_test_test_zones_on_one_z1, patch_test_test_zones_on_one_z2, patch_test_test_zones_on_one_z3};

const byte** patches[] = {patch_check_sliders, patch_check_sliders_1, patch_check_sliders_2, patch_check_sliders_3, patch_test_test_all1, patch_test_test_even_odd, patch_test_test_zones_on_one};

  prog_char patch_name_0[] PROGMEM = "check_sliders";
  prog_char patch_name_1[] PROGMEM = "check_sliders_1";
  prog_char patch_name_2[] PROGMEM = "check_sliders_2";
  prog_char patch_name_3[] PROGMEM = "check_sliders_3";
  prog_char patch_name_4[] PROGMEM = "test_test_all1";
  prog_char patch_name_5[] PROGMEM = "test_test_even_odd";
  prog_char patch_name_6[] PROGMEM = "test_test_zones_on_one";
PROGMEM const char *patch_names[] = {patch_name_0, patch_name_1, patch_name_2, patch_name_3, patch_name_4, patch_name_5, patch_name_6};

const byte Patch_Count = count_of(patches);

// End Generated by make patches.h

